# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e395c496d595d6eebe5be24ba038b1b41564c688c3e424ed73e7c03152aabfeba8deec2b766a7c9f9a8586707f8f36c666564418814de1cce6235b67ae7e7ea0

test:
  secret_key_base: 1bf15d4b103c87765e44683261a8af1d862ba9ed81a39afaf711617b87509d77f5d09df9f8a62f9dfafc6e4c47e90b553647678e6370580aeb2687915d2661c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
